### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by danielkucera** [scanlime/flipsyfat#1]
Hi @scanlime ,

can you please share versions (git commit) of misoc and migen you have used?

Latest versions fail with:
```$ make
flipsyfat/targets/papilio_pro.py
Traceback (most recent call last):
  File "flipsyfat/targets/papilio_pro.py", line 95, in <module>
    main()
  File "flipsyfat/targets/papilio_pro.py", line 89, in main
    soc = Flipsyfat(**soc_sdram_argdict(args))
  File "flipsyfat/targets/papilio_pro.py", line 51, in __init__
    BaseSoC.__init__(self, uart_baudrate=500000, **kwargs)
  File "/home/danman/.local/lib/python3.6/site-packages/misoc/targets/papilio_pro.py", line 87, in __init__
    self.register_rom(self.spiflash.bus)
  File "/home/danman/.local/lib/python3.6/site-packages/misoc/integration/soc_core.py", line 140, in register_rom
    assert self.cpu_reset_address < rom_size
AssertionError
Makefile:10: recipe for target 'synth' failed
make: *** [synth] Error 1
```

**Comment by danielkucera** [comment]
Ok, it's a bug in misoc: https://github.com/m-labs/misoc/issues/60

**Comment by danielkucera** [comment]
nvm, fixed in https://github.com/danielkucera/flipsyfat/commit/01d4a7938875e15b75d8833e99dc33d5d7111df6
